### Libraries

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
import os
import warnings
warnings.filterwarnings("ignore")

### Cleaning 2022 Data

In [2]:
# Set the path to the folder where the CSV files are stored
folder_path = "/Users/maynardemmanuelmiranda/Desktop/CDA Project/Data/Data/2022"

# Get a list of all the CSV files in the folder
csv_files = [f for f in os.listdir(folder_path) if f.endswith('.csv')]

# Create an empty list to store the dataframes
dfs = []

# Loop through each CSV file and append the dataframe to the list
for file in csv_files:
    file_path = os.path.join(folder_path, file)
    df = pd.read_csv(file_path)
    dfs.append(df)

# Concatenate all the dataframes into one
combined_df_2022 = pd.concat(dfs, ignore_index=True)

# Print the first 5 rows of the combined dataframe
combined_df_2022.head()

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_AIRLINE_ID,OP_CARRIER,TAIL_NUM,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_STATE_FIPS,ORIGIN_STATE_NM,ORIGIN_WAC,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,DEST,DEST_CITY_NAME,DEST_STATE_ABR,DEST_STATE_FIPS,DEST_STATE_NM,DEST_WAC,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,DEP_DEL15,DEP_DELAY_GROUP,DEP_TIME_BLK,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,ARR_DEL15,ARR_DELAY_GROUP,ARR_TIME_BLK,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,FLIGHTS,DISTANCE,DISTANCE_GROUP,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,FIRST_DEP_TIME,TOTAL_ADD_GTIME,LONGEST_ADD_GTIME,DIV_AIRPORT_LANDINGS,DIV_REACHED_DEST,DIV_ACTUAL_ELAPSED_TIME,DIV_ARR_DELAY,DIV_DISTANCE,DIV1_AIRPORT,DIV1_AIRPORT_ID,DIV1_AIRPORT_SEQ_ID,DIV1_WHEELS_ON,DIV1_TOTAL_GTIME,DIV1_LONGEST_GTIME,DIV1_WHEELS_OFF,DIV1_TAIL_NUM,DIV2_AIRPORT,DIV2_AIRPORT_ID,DIV2_AIRPORT_SEQ_ID,DIV2_WHEELS_ON,DIV2_TOTAL_GTIME,DIV2_LONGEST_GTIME,DIV2_WHEELS_OFF,DIV2_TAIL_NUM,DIV3_AIRPORT,DIV3_AIRPORT_ID,DIV3_AIRPORT_SEQ_ID,DIV3_WHEELS_ON,DIV3_TOTAL_GTIME,DIV3_LONGEST_GTIME,DIV3_WHEELS_OFF,DIV3_TAIL_NUM,DIV4_AIRPORT,DIV4_AIRPORT_ID,DIV4_AIRPORT_SEQ_ID,DIV4_WHEELS_ON,DIV4_TOTAL_GTIME,DIV4_LONGEST_GTIME,DIV4_WHEELS_OFF,DIV4_TAIL_NUM,DIV5_AIRPORT,DIV5_AIRPORT_ID,DIV5_AIRPORT_SEQ_ID,DIV5_WHEELS_ON,DIV5_TOTAL_GTIME,DIV5_LONGEST_GTIME,DIV5_WHEELS_OFF,DIV5_TAIL_NUM
0,2022,1,1,1,6,1/1/2022 12:00:00 AM,9E,20363,9E,N138EV,4732,10135,1013506,30135,ABE,"Allentown/Bethlehem/Easton, PA",PA,42,Pennsylvania,23,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,43,1015,1014.0,-1.0,0.0,0.0,-1.0,1000-1059,14.0,1028.0,1147.0,7.0,1209,1154.0,-15.0,0.0,0.0,-1.0,1200-1259,0.0,NaN,0.0,114.0,100.0,79.0,1.0,425.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022,1,1,1,6,1/1/2022 12:00:00 AM,9E,20363,9E,N138EV,4979,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,43,14524,1452401,34524,RIC,"Richmond, VA",VA,51,Virginia,38,2130,NaN,NaN,NaN,NaN,NaN,2100-2159,NaN,NaN,NaN,NaN,2305,NaN,NaN,NaN,NaN,NaN,2300-2359,1.0,B,0.0,95.0,NaN,NaN,1.0,456.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022,1,1,1,6,1/1/2022 12:00:00 AM,9E,20363,9E,N138EV,5430,10135,1013506,30135,ABE,"Allentown/Bethlehem/Easton, PA",PA,42,Pennsylvania,23,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,43,1700,NaN,NaN,NaN,NaN,NaN,1700-1759,NaN,NaN,NaN,NaN,1853,NaN,NaN,NaN,NaN,NaN,1800-1859,1.0,B,0.0,113.0,NaN,NaN,1.0,425.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022,1,1,1,6,1/1/2022 12:00:00 AM,9E,20363,9E,N138EV,5430,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,43,10135,1013506,30135,ABE,"Allentown/Bethlehem/Easton, PA",PA,42,Pennsylvania,23,1422,1419.0,-3.0,0.0,0.0,-1.0,1400-1459,11.0,1430.0,1526.0,3.0,1548,1529.0,-19.0,0.0,0.0,-2.0,1500-1559,0.0,NaN,0.0,86.0,70.0,56.0,1.0,425.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022,1,1,1,6,1/1/2022 12:00:00 AM,9E,20363,9E,N146PQ,4722,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,43,11423,1142307,31423,DSM,"Des Moines, IA",IA,19,Iowa,61,1255,NaN,NaN,NaN,NaN,NaN,1200-1259,NaN,NaN,NaN,NaN,1348,NaN,NaN,NaN,NaN,NaN,1300-1359,1.0,B,0.0,113.0,NaN,NaN,1.0,534.0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# select columns that do not start with "DIV"
filtered_df = combined_df_2022.filter(regex='^(?!DIV)')

# create a new DataFrame with only the selected columns
combined_df_2022 = pd.DataFrame(filtered_df)

In [4]:
# Convert the 'FL_DATE' column to a datetime data type
combined_df_2022['FL_DATE'] = pd.to_datetime(combined_df_2022['FL_DATE'])

# Extract the date part only and overwrite the 'FL_DATE' column
combined_df_2022['FL_DATE'] = combined_df_2022['FL_DATE'].dt.date

# Print the first 5 rows of the modified DataFrame to verify the changes
combined_df_2022.head()

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_AIRLINE_ID,OP_CARRIER,TAIL_NUM,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_STATE_FIPS,ORIGIN_STATE_NM,ORIGIN_WAC,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,DEST,DEST_CITY_NAME,DEST_STATE_ABR,DEST_STATE_FIPS,DEST_STATE_NM,DEST_WAC,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,DEP_DEL15,DEP_DELAY_GROUP,DEP_TIME_BLK,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,ARR_DEL15,ARR_DELAY_GROUP,ARR_TIME_BLK,CANCELLED,CANCELLATION_CODE,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,FLIGHTS,DISTANCE,DISTANCE_GROUP,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,FIRST_DEP_TIME,TOTAL_ADD_GTIME,LONGEST_ADD_GTIME
0,2022,1,1,1,6,2022-01-01,9E,20363,9E,N138EV,4732,10135,1013506,30135,ABE,"Allentown/Bethlehem/Easton, PA",PA,42,Pennsylvania,23,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,43,1015,1014.0,-1.0,0.0,0.0,-1.0,1000-1059,14.0,1028.0,1147.0,7.0,1209,1154.0,-15.0,0.0,0.0,-1.0,1200-1259,0.0,NaN,114.0,100.0,79.0,1.0,425.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022,1,1,1,6,2022-01-01,9E,20363,9E,N138EV,4979,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,43,14524,1452401,34524,RIC,"Richmond, VA",VA,51,Virginia,38,2130,NaN,NaN,NaN,NaN,NaN,2100-2159,NaN,NaN,NaN,NaN,2305,NaN,NaN,NaN,NaN,NaN,2300-2359,1.0,B,95.0,NaN,NaN,1.0,456.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022,1,1,1,6,2022-01-01,9E,20363,9E,N138EV,5430,10135,1013506,30135,ABE,"Allentown/Bethlehem/Easton, PA",PA,42,Pennsylvania,23,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,43,1700,NaN,NaN,NaN,NaN,NaN,1700-1759,NaN,NaN,NaN,NaN,1853,NaN,NaN,NaN,NaN,NaN,1800-1859,1.0,B,113.0,NaN,NaN,1.0,425.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022,1,1,1,6,2022-01-01,9E,20363,9E,N138EV,5430,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,43,10135,1013506,30135,ABE,"Allentown/Bethlehem/Easton, PA",PA,42,Pennsylvania,23,1422,1419.0,-3.0,0.0,0.0,-1.0,1400-1459,11.0,1430.0,1526.0,3.0,1548,1529.0,-19.0,0.0,0.0,-2.0,1500-1559,0.0,NaN,86.0,70.0,56.0,1.0,425.0,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022,1,1,1,6,2022-01-01,9E,20363,9E,N146PQ,4722,11433,1143302,31295,DTW,"Detroit, MI",MI,26,Michigan,43,11423,1142307,31423,DSM,"Des Moines, IA",IA,19,Iowa,61,1255,NaN,NaN,NaN,NaN,NaN,1200-1259,NaN,NaN,NaN,NaN,1348,NaN,NaN,NaN,NaN,NaN,1300-1359,1.0,B,113.0,NaN,NaN,1.0,534.0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Not needed columns
cols_to_drop = ['OP_UNIQUE_CARRIER', 'OP_CARRIER_AIRLINE_ID', 'TAIL_NUM',
                'ORIGIN_AIRPORT_SEQ_ID', 'ORIGIN_CITY_MARKET_ID', 'ORIGIN_CITY_NAME',
                'ORIGIN_STATE_FIPS', 'ORIGIN_STATE_NM', 'ORIGIN_WAC',
                'DEST_AIRPORT_SEQ_ID', 'DEST_CITY_MARKET_ID', 'DEST_CITY_NAME',
                'DEST_STATE_NM', 'DEST_WAC']

# Drop the columns from the DataFrame
combined_df_2022 = combined_df_2022.drop(columns=cols_to_drop)

In [6]:
# Top 10 busiest airports
valid_values = ['LAX', 'ORD', 'DEN', 'ATL', 'BOS', 'SFO', 'SEA', 'EWR', 'DFW', 'MCO']

# Filter the DataFrame to only include rows with valid values in the 'ORIGIN' and 'DEST' columns
combined_df_2022 = combined_df_2022[combined_df_2022['ORIGIN'].isin(valid_values) & combined_df_2022['DEST'].isin(valid_values)]

# Reset the index of the filtered DataFrame
combined_df_2022 = combined_df_2022.reset_index(drop=True)
#combined_df_2022 = combined_df_2022.dropna(axis=0)

# Print the first 5 rows of the filtered DataFrame to verify the changes
combined_df_2022.head()

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN,ORIGIN_STATE_ABR,DEST_AIRPORT_ID,DEST,DEST_STATE_ABR,DEST_STATE_FIPS,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,DEP_DEL15,DEP_DELAY_GROUP,DEP_TIME_BLK,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,ARR_DEL15,ARR_DELAY_GROUP,ARR_TIME_BLK,CANCELLED,CANCELLATION_CODE,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,FLIGHTS,DISTANCE,DISTANCE_GROUP,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,FIRST_DEP_TIME,TOTAL_ADD_GTIME,LONGEST_ADD_GTIME
0,2022,1,1,1,6,2022-01-01,AA,2453,12892,LAX,CA,10721,BOS,MA,25,2359,2358.0,-1.0,0.0,0.0,-1.0,2300-2359,20.0,18.0,814.0,11.0,822,825.0,3.0,3.0,0.0,0.0,0800-0859,0.0,NaN,323.0,327.0,296.0,1.0,2611.0,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022,1,1,1,6,2022-01-01,AA,2455,10721,BOS,MA,12892,LAX,CA,6,1000,954.0,-6.0,0.0,0.0,-1.0,1000-1059,14.0,1008.0,1327.0,8.0,1348,1335.0,-13.0,0.0,0.0,-1.0,1300-1359,0.0,NaN,408.0,401.0,379.0,1.0,2611.0,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022,1,1,1,6,2022-01-01,AA,1687,12892,LAX,CA,10721,BOS,MA,25,1200,1151.0,-9.0,0.0,0.0,-1.0,1200-1259,10.0,1201.0,1934.0,6.0,2023,1940.0,-43.0,0.0,0.0,-2.0,2000-2059,0.0,NaN,323.0,289.0,273.0,1.0,2611.0,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022,1,1,1,6,2022-01-01,AA,382,12892,LAX,CA,10721,BOS,MA,25,1430,1503.0,33.0,33.0,1.0,2.0,1400-1459,11.0,1514.0,2247.0,6.0,2252,2253.0,1.0,1.0,0.0,0.0,2200-2259,0.0,NaN,322.0,290.0,273.0,1.0,2611.0,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022,1,1,1,6,2022-01-01,AA,946,10721,BOS,MA,12892,LAX,CA,6,800,757.0,-3.0,0.0,0.0,-1.0,0800-0859,25.0,822.0,1144.0,11.0,1148,1155.0,7.0,7.0,0.0,0.0,1100-1159,0.0,NaN,408.0,418.0,382.0,1.0,2611.0,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Cleaning 2021 Data

In [7]:
# Set the path to the folder where the CSV files are stored
folder_path = "/Users/maynardemmanuelmiranda/Desktop/CDA Project/Data/Data/2021"

# Get a list of all the CSV files in the folder
csv_files = [f for f in os.listdir(folder_path) if f.endswith('.csv')]

# Create an empty list to store the dataframes
dfs = []

# Loop through each CSV file and append the dataframe to the list
for file in csv_files:
    file_path = os.path.join(folder_path, file)
    df = pd.read_csv(file_path)
    dfs.append(df)

# Concatenate all the dataframes into one
combined_df_2021 = pd.concat(dfs, ignore_index=True)

# Print the first 5 rows of the combined dataframe
combined_df_2021.head()

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_AIRLINE_ID,OP_CARRIER,TAIL_NUM,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_STATE_FIPS,ORIGIN_STATE_NM,ORIGIN_WAC,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,DEST,DEST_CITY_NAME,DEST_STATE_ABR,DEST_STATE_FIPS,DEST_STATE_NM,DEST_WAC,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,DEP_DEL15,DEP_DELAY_GROUP,DEP_TIME_BLK,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,ARR_DEL15,ARR_DELAY_GROUP,ARR_TIME_BLK,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,FLIGHTS,DISTANCE,DISTANCE_GROUP,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,FIRST_DEP_TIME,TOTAL_ADD_GTIME,LONGEST_ADD_GTIME,DIV_AIRPORT_LANDINGS,DIV_REACHED_DEST,DIV_ACTUAL_ELAPSED_TIME,DIV_ARR_DELAY,DIV_DISTANCE,DIV1_AIRPORT,DIV1_AIRPORT_ID,DIV1_AIRPORT_SEQ_ID,DIV1_WHEELS_ON,DIV1_TOTAL_GTIME,DIV1_LONGEST_GTIME,DIV1_WHEELS_OFF,DIV1_TAIL_NUM,DIV2_AIRPORT,DIV2_AIRPORT_ID,DIV2_AIRPORT_SEQ_ID,DIV2_WHEELS_ON,DIV2_TOTAL_GTIME,DIV2_LONGEST_GTIME,DIV2_WHEELS_OFF,DIV2_TAIL_NUM,DIV3_AIRPORT,DIV3_AIRPORT_ID,DIV3_AIRPORT_SEQ_ID,DIV3_WHEELS_ON,DIV3_TOTAL_GTIME,DIV3_LONGEST_GTIME,DIV3_WHEELS_OFF,DIV3_TAIL_NUM,DIV4_AIRPORT,DIV4_AIRPORT_ID,DIV4_AIRPORT_SEQ_ID,DIV4_WHEELS_ON,DIV4_TOTAL_GTIME,DIV4_LONGEST_GTIME,DIV4_WHEELS_OFF,DIV4_TAIL_NUM,DIV5_AIRPORT,DIV5_AIRPORT_ID,DIV5_AIRPORT_SEQ_ID,DIV5_WHEELS_ON,DIV5_TOTAL_GTIME,DIV5_LONGEST_GTIME,DIV5_WHEELS_OFF,DIV5_TAIL_NUM
0,2021,1,1,1,5,1/1/2021 12:00:00 AM,9E,20363,9E,N131EV,4656,10397,1039707,30397,ATL,"Atlanta, GA",GA,13,Georgia,34,12448,1244807,32448,JAN,"Jackson/Vicksburg, MS",MS,28,Mississippi,53,1030,1446.0,256.0,256.0,1.0,12.0,1000-1059,10.0,1456.0,1457.0,5.0,1053,1502.0,249.0,249.0,1.0,12.0,1000-1059,0.0,NaN,0.0,83.0,76.0,61.0,1.0,341.0,2,49.0,0.0,0.0,0.0,200.0,1408.0,30.0,30.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021,1,1,1,5,1/1/2021 12:00:00 AM,9E,20363,9E,N131EV,4656,12448,1244807,32448,JAN,"Jackson/Vicksburg, MS",MS,28,Mississippi,53,10397,1039707,30397,ATL,"Atlanta, GA",GA,13,Georgia,34,1145,1542.0,237.0,237.0,1.0,12.0,1100-1159,9.0,1551.0,1737.0,12.0,1411,1749.0,218.0,218.0,1.0,12.0,1400-1459,0.0,NaN,0.0,86.0,67.0,46.0,1.0,341.0,2,0.0,0.0,0.0,0.0,218.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021,1,1,1,5,1/1/2021 12:00:00 AM,9E,20363,9E,N131EV,4889,10397,1039707,30397,ATL,"Atlanta, GA",GA,13,Georgia,34,11996,1199603,31871,GSP,"Greer, SC",SC,45,South Carolina,37,2030,2044.0,14.0,14.0,0.0,0.0,2000-2059,13.0,2057.0,2124.0,4.0,2121,2128.0,7.0,7.0,0.0,0.0,2100-2159,0.0,NaN,0.0,51.0,44.0,27.0,1.0,153.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021,1,1,1,5,1/1/2021 12:00:00 AM,9E,20363,9E,N131EV,4936,13851,1385103,33851,OKC,"Oklahoma City, OK",OK,40,Oklahoma,73,10397,1039707,30397,ATL,"Atlanta, GA",GA,13,Georgia,34,600,856.0,176.0,176.0,1.0,11.0,0600-0659,87.0,1023.0,1253.0,8.0,903,1301.0,238.0,238.0,1.0,12.0,0900-0959,0.0,NaN,0.0,123.0,185.0,90.0,1.0,761.0,4,0.0,176.0,62.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021,1,1,1,5,1/1/2021 12:00:00 AM,9E,20363,9E,N132EV,4698,10599,1059904,30599,BHM,"Birmingham, AL",AL,1,Alabama,51,10397,1039707,30397,ATL,"Atlanta, GA",GA,13,Georgia,34,1505,1500.0,-5.0,0.0,0.0,-1.0,1500-1559,12.0,1512.0,1650.0,11.0,1704,1701.0,-3.0,0.0,0.0,-1.0,1700-1759,0.0,NaN,0.0,59.0,61.0,38.0,1.0,134.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# Convert the 'FL_DATE' column to a datetime data type
combined_df_2021['FL_DATE'] = pd.to_datetime(combined_df_2021['FL_DATE'])

# Extract the date part only and overwrite the 'FL_DATE' column
combined_df_2021['FL_DATE'] = combined_df_2021['FL_DATE'].dt.date

# Print the first 5 rows of the modified DataFrame to verify the changes
combined_df_2021.head()

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_UNIQUE_CARRIER,OP_CARRIER_AIRLINE_ID,OP_CARRIER,TAIL_NUM,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_STATE_FIPS,ORIGIN_STATE_NM,ORIGIN_WAC,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,DEST_CITY_MARKET_ID,DEST,DEST_CITY_NAME,DEST_STATE_ABR,DEST_STATE_FIPS,DEST_STATE_NM,DEST_WAC,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,DEP_DEL15,DEP_DELAY_GROUP,DEP_TIME_BLK,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,ARR_DEL15,ARR_DELAY_GROUP,ARR_TIME_BLK,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,FLIGHTS,DISTANCE,DISTANCE_GROUP,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,FIRST_DEP_TIME,TOTAL_ADD_GTIME,LONGEST_ADD_GTIME,DIV_AIRPORT_LANDINGS,DIV_REACHED_DEST,DIV_ACTUAL_ELAPSED_TIME,DIV_ARR_DELAY,DIV_DISTANCE,DIV1_AIRPORT,DIV1_AIRPORT_ID,DIV1_AIRPORT_SEQ_ID,DIV1_WHEELS_ON,DIV1_TOTAL_GTIME,DIV1_LONGEST_GTIME,DIV1_WHEELS_OFF,DIV1_TAIL_NUM,DIV2_AIRPORT,DIV2_AIRPORT_ID,DIV2_AIRPORT_SEQ_ID,DIV2_WHEELS_ON,DIV2_TOTAL_GTIME,DIV2_LONGEST_GTIME,DIV2_WHEELS_OFF,DIV2_TAIL_NUM,DIV3_AIRPORT,DIV3_AIRPORT_ID,DIV3_AIRPORT_SEQ_ID,DIV3_WHEELS_ON,DIV3_TOTAL_GTIME,DIV3_LONGEST_GTIME,DIV3_WHEELS_OFF,DIV3_TAIL_NUM,DIV4_AIRPORT,DIV4_AIRPORT_ID,DIV4_AIRPORT_SEQ_ID,DIV4_WHEELS_ON,DIV4_TOTAL_GTIME,DIV4_LONGEST_GTIME,DIV4_WHEELS_OFF,DIV4_TAIL_NUM,DIV5_AIRPORT,DIV5_AIRPORT_ID,DIV5_AIRPORT_SEQ_ID,DIV5_WHEELS_ON,DIV5_TOTAL_GTIME,DIV5_LONGEST_GTIME,DIV5_WHEELS_OFF,DIV5_TAIL_NUM
0,2021,1,1,1,5,2021-01-01,9E,20363,9E,N131EV,4656,10397,1039707,30397,ATL,"Atlanta, GA",GA,13,Georgia,34,12448,1244807,32448,JAN,"Jackson/Vicksburg, MS",MS,28,Mississippi,53,1030,1446.0,256.0,256.0,1.0,12.0,1000-1059,10.0,1456.0,1457.0,5.0,1053,1502.0,249.0,249.0,1.0,12.0,1000-1059,0.0,NaN,0.0,83.0,76.0,61.0,1.0,341.0,2,49.0,0.0,0.0,0.0,200.0,1408.0,30.0,30.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021,1,1,1,5,2021-01-01,9E,20363,9E,N131EV,4656,12448,1244807,32448,JAN,"Jackson/Vicksburg, MS",MS,28,Mississippi,53,10397,1039707,30397,ATL,"Atlanta, GA",GA,13,Georgia,34,1145,1542.0,237.0,237.0,1.0,12.0,1100-1159,9.0,1551.0,1737.0,12.0,1411,1749.0,218.0,218.0,1.0,12.0,1400-1459,0.0,NaN,0.0,86.0,67.0,46.0,1.0,341.0,2,0.0,0.0,0.0,0.0,218.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021,1,1,1,5,2021-01-01,9E,20363,9E,N131EV,4889,10397,1039707,30397,ATL,"Atlanta, GA",GA,13,Georgia,34,11996,1199603,31871,GSP,"Greer, SC",SC,45,South Carolina,37,2030,2044.0,14.0,14.0,0.0,0.0,2000-2059,13.0,2057.0,2124.0,4.0,2121,2128.0,7.0,7.0,0.0,0.0,2100-2159,0.0,NaN,0.0,51.0,44.0,27.0,1.0,153.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021,1,1,1,5,2021-01-01,9E,20363,9E,N131EV,4936,13851,1385103,33851,OKC,"Oklahoma City, OK",OK,40,Oklahoma,73,10397,1039707,30397,ATL,"Atlanta, GA",GA,13,Georgia,34,600,856.0,176.0,176.0,1.0,11.0,0600-0659,87.0,1023.0,1253.0,8.0,903,1301.0,238.0,238.0,1.0,12.0,0900-0959,0.0,NaN,0.0,123.0,185.0,90.0,1.0,761.0,4,0.0,176.0,62.0,0.0,0.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021,1,1,1,5,2021-01-01,9E,20363,9E,N132EV,4698,10599,1059904,30599,BHM,"Birmingham, AL",AL,1,Alabama,51,10397,1039707,30397,ATL,"Atlanta, GA",GA,13,Georgia,34,1505,1500.0,-5.0,0.0,0.0,-1.0,1500-1559,12.0,1512.0,1650.0,11.0,1704,1701.0,-3.0,0.0,0.0,-1.0,1700-1759,0.0,NaN,0.0,59.0,61.0,38.0,1.0,134.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
valid_values = ['LAX', 'ORD', 'DEN', 'ATL', 'BOS', 'SFO', 'SEA', 'EWR', 'DFW', 'MCO']

# Filter the DataFrame to only include rows with valid values in the 'ORIGIN' and 'DEST' columns
combined_df_2021 = combined_df_2021[combined_df_2021['ORIGIN'].isin(valid_values) & combined_df_2021['DEST'].isin(valid_values)]

# Reset the index of the filtered DataFrame
combined_df_2021 = combined_df_2021.reset_index(drop=True)

In [10]:
# Get a list of all the columns in combined_df_2022
cols_2022 = combined_df_2022.columns.tolist()

# Subset combined_df_2021 to only keep columns present in combined_df_2022
combined_df_2021 = combined_df_2021.loc[:, cols_2022]

### Concatenate 2021 and 2022 Data

In [11]:
df_final = pd.concat([combined_df_2021, combined_df_2022])

In [12]:
# Create a dictionary with the distance codes and descriptions
distance_dict = {
    1: 'Less Than 250 Miles',
    2: '250-499 Miles',
    3: '500-749 Miles',
    4: '750-999 Miles',
    5: '1000-1249 Miles',
    6: '1250-1499 Miles',
    7: '1500-1749 Miles',
    8: '1750-1999 Miles',
    9: '2000-2249 Miles',
    10: '2250-2499 Miles',
    11: '2500 Miles and Greater'
}

# Create the distance_group_df DataFrame from the dictionary
distance_group_df = pd.DataFrame.from_dict(distance_dict, orient='index', columns=['Description'])
distance_group_df.index.name = 'Code'

# Print the distance_group_df DataFrame
print(distance_group_df)

                 Description
Code
1        Less Than 250 Miles
2              250-499 Miles
3              500-749 Miles
4              750-999 Miles
5            1000-1249 Miles
6            1250-1499 Miles
7            1500-1749 Miles
8            1750-1999 Miles
9            2000-2249 Miles
10           2250-2499 Miles
11    2500 Miles and Greater

In [13]:
# Map the distance codes to the corresponding descriptions using distance_group_df
df_final['DISTANCE_GROUP'] = df_final['DISTANCE_GROUP'].map(distance_group_df['Description'])

In [14]:
data = {'Code': [-2., -1., 0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 10., 11., 12.],
        'Description': ['On time/Early', 'On time/Early', 'Delay between 0 and 14 minutes',
                         'Delay between 15 to 29 minutes', 'Delay between 30 to 44 minutes',
                         'Delay between 45 to 59 minutes', 'Delay between 60 to 74 minutes',
                         'Delay between 75 to 89 minutes', 'Delay between 90 to 104 minutes',
                         'Delay between 105 to 119 minutes', 'Delay between 120 to 134 minutes',
                         'Delay between 135 to 149 minutes', 'Delay between 150 to 164 minutes',
                         'Delay between 165 to 179 minutes', 'Delay >= 180 minutes']}

Delay_Group_df = pd.DataFrame(data)

In [15]:
data = {'Code': [-2., -1., 0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 10., 11., 12.],
        'Description': ['On time/Early', 'On time/Early', 'Delay between 0 and 14 minutes',
                         'Delay between 15 to 29 minutes', 'Delay between 30 to 44 minutes',
                         'Delay between 45 to 59 minutes', 'Delay between 60 to 74 minutes',
                         'Delay between 75 to 89 minutes', 'Delay between 90 to 104 minutes',
                         'Delay between 105 to 119 minutes', 'Delay between 120 to 134 minutes',
                         'Delay between 135 to 149 minutes', 'Delay between 150 to 164 minutes',
                         'Delay between 165 to 179 minutes', 'Delay >= 180 minutes']}

# Create a dictionary to map the codes to their descriptions
mapping = {code: desc for code, desc in zip(data['Code'], data['Description'])}

# Map the codes in the "DEP_DELAY_GROUP" column to their descriptions
df_final['DEP_DELAY_GROUP_DESCRIPTION'] = df_final['DEP_DELAY_GROUP'].map(mapping)

In [16]:
df_final = df_final.drop(['DEST_STATE_FIPS', 'CRS_DEP_TIME', 'DEP_DELAY', 'DEP_DELAY_NEW', 'DEP_DEL15', 'DEP_DELAY_GROUP', 'DEP_TIME_BLK'], axis=1)

In [17]:
df_final["DEP_TIME"] = pd.to_datetime(df_final["DEP_TIME"], format='%H%M', errors='coerce').dt.strftime('%H:%M')
df_final["WHEELS_OFF"] = pd.to_datetime(df_final["WHEELS_OFF"], format='%H%M', errors='coerce').dt.strftime('%H:%M')
df_final["WHEELS_ON"] = pd.to_datetime(df_final["WHEELS_ON"], format='%H%M', errors='coerce').dt.strftime('%H:%M')
df_final["ARR_TIME"] = pd.to_datetime(df_final["ARR_TIME"], format='%H%M', errors='coerce').dt.strftime('%H:%M')

In [18]:
df_final = df_final.drop(['CRS_ARR_TIME', 'ARR_DELAY', 'ARR_DELAY_NEW', 'ARR_DEL15', 'ARR_TIME_BLK'], axis=1)

In [19]:
# Map the codes in the "DEP_DELAY_GROUP" column to their descriptions
df_final['ARR_DELAY_GROUP_DESCRIPTION'] = df_final['ARR_DELAY_GROUP'].map(mapping)

In [20]:
df_final = df_final.drop(['ARR_DELAY_GROUP','CRS_ELAPSED_TIME', 'FLIGHTS'], axis=1)
#df_final = df_final.dropna()

In [21]:
# convert "DEP_TIME" and "ARR_TIME" columns to datetime objects
df_final["DEP_TIME"] = pd.to_datetime(df_final["DEP_TIME"], format="%H:%M")
df_final["ARR_TIME"] = pd.to_datetime(df_final["ARR_TIME"], format="%H:%M")

# create a list of time range bins for the cut function
time_bins = [pd.to_datetime("00:00", format="%H:%M"), pd.to_datetime("05:59", format="%H:%M"), pd.to_datetime("11:59", format="%H:%M"), pd.to_datetime("17:59", format="%H:%M"), pd.to_datetime("23:59", format="%H:%M")]

# create a list of labels for the time range bins
time_labels = ["Early morning", "Morning", "Afternoon", "Evening"]

# create new columns "DEP_TIME_GROUP" and "ARR_TIME_GROUP"
df_final["DEP_TIME_GROUP"] = pd.cut(df_final["DEP_TIME"], bins=time_bins, labels=time_labels, include_lowest=True)
df_final["ARR_TIME_GROUP"] = pd.cut(df_final["ARR_TIME"], bins=time_bins, labels=time_labels, include_lowest=True)

df_final.head()

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN,ORIGIN_STATE_ABR,DEST_AIRPORT_ID,DEST,DEST_STATE_ABR,DEP_TIME,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,ARR_TIME,CANCELLED,CANCELLATION_CODE,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,DISTANCE_GROUP,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,FIRST_DEP_TIME,TOTAL_ADD_GTIME,LONGEST_ADD_GTIME,DEP_DELAY_GROUP_DESCRIPTION,ARR_DELAY_GROUP_DESCRIPTION,DEP_TIME_GROUP,ARR_TIME_GROUP
0,2021,1,1,1,5,2021-01-01,AA,278,10721,BOS,MA,13930,ORD,IL,1900-01-01 05:17:00,18.0,05:35,07:11,12.0,1900-01-01 07:23:00,0.0,NaN,186.0,156.0,867.0,750-999 Miles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,On time/Early,Delay between 0 and 14 minutes,Early morning,Morning
1,2021,1,1,1,5,2021-01-01,AA,1890,11298,DFW,TX,14771,SFO,CA,1900-01-01 14:37:00,25.0,15:02,16:19,8.0,1900-01-01 16:27:00,0.0,NaN,230.0,197.0,1464.0,1250-1499 Miles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,On time/Early,On time/Early,Afternoon,Afternoon
2,2021,1,1,1,5,2021-01-01,AA,1121,13204,MCO,FL,13930,ORD,IL,1900-01-01 14:49:00,43.0,15:32,16:56,9.0,1900-01-01 17:05:00,0.0,NaN,196.0,144.0,1005.0,1000-1249 Miles,0.0,0.0,56.0,0.0,12.0,NaN,NaN,NaN,Delay between 45 to 59 minutes,Delay between 60 to 74 minutes,Afternoon,Afternoon
3,2021,1,1,1,5,2021-01-01,AA,1878,13930,ORD,IL,13204,MCO,FL,1900-01-01 09:39:00,17.0,09:56,13:16,5.0,1900-01-01 13:21:00,0.0,NaN,162.0,140.0,1005.0,1000-1249 Miles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Delay between 0 and 14 minutes,Delay between 0 and 14 minutes,Morning,Afternoon
4,2021,1,1,1,5,2021-01-01,AA,2715,13930,ORD,IL,12892,LAX,CA,1900-01-01 19:16:00,15.0,19:31,21:09,4.0,1900-01-01 21:13:00,0.0,NaN,237.0,218.0,1744.0,1500-1749 Miles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Delay between 15 to 29 minutes,On time/Early,Evening,Evening

In [22]:
df_final.loc[df_final['CANCELLED'] == 0.0, ['CARRIER_DELAY', 'WEATHER_DELAY', 'NAS_DELAY', 'SECURITY_DELAY', 'LATE_AIRCRAFT_DELAY']] = df_final.loc[df_final['CANCELLED'] == 0.0, ['CARRIER_DELAY', 'WEATHER_DELAY', 'NAS_DELAY', 'SECURITY_DELAY', 'LATE_AIRCRAFT_DELAY']].fillna(0)

In [23]:
df_final.loc[df_final['CANCELLED'] == 0.0, 'CANCELLATION_CODE'] = df_final.loc[df_final['CANCELLED'] == 0.0, 'CANCELLATION_CODE'].fillna('Not Applicable')

In [24]:
code_map = {'A': 'Carrier', 'B': 'Weather', 'C': 'National Air System', 'D': 'Security'}

df_final['CANCELLATION_CODE'] = df_final['CANCELLATION_CODE'].replace(code_map)

In [25]:
df_final = df_final.drop(['FIRST_DEP_TIME', 'TOTAL_ADD_GTIME', 'LONGEST_ADD_GTIME'], axis=1)

In [26]:
df_final['DEP_TIME'] = pd.to_datetime(df_final['DEP_TIME']).dt.strftime('%H:%M')
df_final['ARR_TIME'] = pd.to_datetime(df_final['ARR_TIME']).dt.strftime('%H:%M')

In [27]:
df_final['DEP_DELAY'] = df_final['DEP_DELAY_GROUP_DESCRIPTION'].apply(lambda x: 0 if x == 'On time/Early' else 1)
df_final['ARR_DELAY'] = df_final['ARR_DELAY_GROUP_DESCRIPTION'].apply(lambda x: 0 if x == 'On time/Early' else 1)

In [28]:
df_final

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN,ORIGIN_STATE_ABR,DEST_AIRPORT_ID,DEST,DEST_STATE_ABR,DEP_TIME,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,ARR_TIME,CANCELLED,CANCELLATION_CODE,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,DISTANCE_GROUP,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,DEP_DELAY_GROUP_DESCRIPTION,ARR_DELAY_GROUP_DESCRIPTION,DEP_TIME_GROUP,ARR_TIME_GROUP,DEP_DELAY,ARR_DELAY
0,2021,1,1,1,5,2021-01-01,AA,278,10721,BOS,MA,13930,ORD,IL,05:17,18.0,05:35,07:11,12.0,07:23,0.0,Not Applicable,186.0,156.0,867.0,750-999 Miles,0.0,0.0,0.0,0.0,0.0,On time/Early,Delay between 0 and 14 minutes,Early morning,Morning,0,1
1,2021,1,1,1,5,2021-01-01,AA,1890,11298,DFW,TX,14771,SFO,CA,14:37,25.0,15:02,16:19,8.0,16:27,0.0,Not Applicable,230.0,197.0,1464.0,1250-1499 Miles,0.0,0.0,0.0,0.0,0.0,On time/Early,On time/Early,Afternoon,Afternoon,0,0
2,2021,1,1,1,5,2021-01-01,AA,1121,13204,MCO,FL,13930,ORD,IL,14:49,43.0,15:32,16:56,9.0,17:05,0.0,Not Applicable,196.0,144.0,1005.0,1000-1249 Miles,0.0,0.0,56.0,0.0,12.0,Delay between 45 to 59 minutes,Delay between 60 to 74 minutes,Afternoon,Afternoon,1,1
3,2021,1,1,1,5,2021-01-01,AA,1878,13930,ORD,IL,13204,MCO,FL,09:39,17.0,09:56,13:16,5.0,13:21,0.0,Not Applicable,162.0,140.0,1005.0,1000-1249 Miles,0.0,0.0,0.0,0.0,0.0,Delay between 0 and 14 minutes,Delay between 0 and 14 minutes,Morning,Afternoon,1,1
4,2021,1,1,1,5,2021-01-01,AA,2715,13930,ORD,IL,12892,LAX,CA,19:16,15.0,19:31,21:09,4.0,21:13,0.0,Not Applicable,237.0,218.0,1744.0,1500-1749 Miles,0.0,0.0,0.0,0.0,0.0,Delay between 15 to 29 minutes,On time/Early,Evening,Evening,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
434501,2022,4,12,31,6,2022-12-31,YX,4805,10721,BOS,MA,13930,ORD,IL,11:29,12.0,11:41,13:05,14.0,13:19,0.0,Not Applicable,170.0,144.0,867.0,750-999 Miles,0.0,0.0,0.0,0.0,0.0,Delay between 15 to 29 minutes,Delay between 0 and 14 minutes,Morning,Afternoon,1,1
434502,2022,4,12,31,6,2022-12-31,YX,3552,10397,ATL,GA,13930,ORD,IL,14:58,21.0,15:19,15:50,12.0,16:02,0.0,Not Applicable,124.0,91.0,606.0,500-749 Miles,0.0,0.0,0.0,0.0,0.0,On time/Early,On time/Early,Afternoon,Afternoon,0,0
434503,2022,4,12,31,6,2022-12-31,YX,3679,13930,ORD,IL,10397,ATL,GA,10:53,27.0,11:20,13:52,7.0,13:59,0.0,Not Applicable,126.0,92.0,606.0,500-749 Miles,0.0,0.0,0.0,0.0,0.0,On time/Early,On time/Early,Morning,Afternoon,0,0
434504,2022,4,12,31,6,2022-12-31,YX,3625,11298,DFW,TX,13930,ORD,IL,14:23,26.0,14:49,16:39,5.0,16:44,0.0,Not Applicable,141.0,110.0,802.0,750-999 Miles,0.0,0.0,0.0,0.0,0.0,On time/Early,On time/Early,Afternoon,Afternoon,0,0
434505,2022,4,12,31,6,2022-12-31,YX,3644,13930,ORD,IL,11298,DFW,TX,10:45,15.0,11:00,12:55,6.0,13:01,0.0,Not Applicable,136.0,115.0,802.0,750-999 Miles,0.0,0.0,0.0,0.0,0.0,On time/Early,On time/Early,Morning,Afternoon,0,0

In [29]:
# Extract the hour part of the DEP_TIME column and store it in a new column DEP_HH
df_final['DEP_HH'] = pd.to_datetime(df_final['DEP_TIME'], format='%H:%M').dt.hour

# Extract the hour part of the ARR_TIME column and store it in a new column ARR_HH
df_final['ARR_HH'] = pd.to_datetime(df_final['ARR_TIME'], format='%H:%M').dt.hour

In [30]:
df_final['CANCELLED'] = df_final['CANCELLED'].astype(int)

In [31]:
def get_flight_result(row):
    if row['ARR_DELAY'] == 0:
        return 0
    elif row['ARR_DELAY'] == 1 and row['CANCELLED'] == 0:
        return 1
    elif row['CANCELLED'] == 1 and row['ARR_DELAY'] == 1 :
        return 2
    else:
        return np.nan

# Apply the function to each row of the DataFrame and store the results in a new column 'Flight Result'
df_final['Flight Result'] = df_final.apply(get_flight_result, axis=1)

In [32]:
df_final[df_final['Flight Result'] == 2]

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,OP_CARRIER,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN,ORIGIN_STATE_ABR,DEST_AIRPORT_ID,DEST,DEST_STATE_ABR,DEP_TIME,TAXI_OUT,WHEELS_OFF,WHEELS_ON,TAXI_IN,ARR_TIME,CANCELLED,CANCELLATION_CODE,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,DISTANCE_GROUP,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,DEP_DELAY_GROUP_DESCRIPTION,ARR_DELAY_GROUP_DESCRIPTION,DEP_TIME_GROUP,ARR_TIME_GROUP,DEP_DELAY,ARR_DELAY,DEP_HH,ARR_HH,Flight Result
70,2021,1,1,1,5,2021-01-01,AA,798,10721,BOS,MA,13930,ORD,IL,NaN,NaN,NaN,NaN,NaN,NaN,1,Weather,NaN,NaN,867.0,750-999 Miles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN,2
71,2021,1,1,1,5,2021-01-01,AA,832,13930,ORD,IL,10721,BOS,MA,NaN,NaN,NaN,NaN,NaN,NaN,1,Weather,NaN,NaN,867.0,750-999 Miles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN,2
174,2021,1,1,1,5,2021-01-01,B6,714,11298,DFW,TX,10721,BOS,MA,NaN,NaN,NaN,NaN,NaN,NaN,1,Carrier,NaN,NaN,1562.0,1500-1749 Miles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN,2
215,2021,1,1,1,5,2021-01-01,DL,1137,10721,BOS,MA,10397,ATL,GA,NaN,NaN,NaN,NaN,NaN,NaN,1,Security,NaN,NaN,946.0,750-999 Miles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN,2
216,2021,1,1,1,5,2021-01-01,DL,415,10397,ATL,GA,10721,BOS,MA,NaN,NaN,NaN,NaN,NaN,NaN,1,Security,NaN,NaN,946.0,750-999 Miles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
433802,2022,4,12,31,6,2022-12-31,B6,1152,13204,MCO,FL,10721,BOS,MA,NaN,NaN,NaN,NaN,NaN,NaN,1,Carrier,NaN,NaN,1121.0,1000-1249 Miles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN,2
433803,2022,4,12,31,6,2022-12-31,B6,2351,10721,BOS,MA,13204,MCO,FL,NaN,NaN,NaN,NaN,NaN,NaN,1,Carrier,NaN,NaN,1121.0,1000-1249 Miles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN,2
434041,2022,4,12,31,6,2022-12-31,NK,1909,13204,MCO,FL,11618,EWR,NJ,NaN,NaN,NaN,NaN,NaN,NaN,1,Weather,NaN,NaN,937.0,750-999 Miles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN,2
434063,2022,4,12,31,6,2022-12-31,NK,1026,10397,ATL,GA,11298,DFW,TX,NaN,NaN,NaN,NaN,NaN,NaN,1,Carrier,NaN,NaN,731.0,500-749 Miles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN,2
434072,2022,4,12,31,6,2022-12-31,NK,1025,11298,DFW,TX,10397,ATL,GA,NaN,NaN,NaN,NaN,NaN,NaN,1,Carrier,NaN,NaN,731.0,500-749 Miles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,NaN,NaN,2

### Export Final Data

In [34]:
flight_final_file = 'flight_final.csv'

df_final.to_csv(flight_final_file, index=False)